package com.app.QuantityMeasurementApp.repository;

import java.util.*;
import java.time.LocalDateTime;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.*;

import com.app.QuantityMeasurementApp.model.*;

/*
 *  REPOSITORY LAYER (DATA ACCESS LAYER)
 *
 *  Purpose:
 *    ✔ Interacts with database
 *    ✔ Performs CRUD operations
 *
 *  JpaRepository<Entity, ID>
 *    ✔ Entity → QuantityMeasurementEntity
 *    ✔ ID type → Long
 */

@Repository   //  Marks this as Spring Data Repository
public interface IQuantityMeasurementRepository 
        extends JpaRepository<QuantityMeasurementEntity, Long> {

    /*
     *  DERIVED QUERY METHODS (AUTO-GENERATED BY SPRING)
     *
     *  Spring creates SQL automatically from method name
     */

    //  Find by operation (ADD, SUBTRACT, etc.)
    List<QuantityMeasurementEntity> findByOperation(String operation);

    //  Find by measurement type (LengthUnit, etc.)
    List<QuantityMeasurementEntity> findByThisMeasurementType(String measurementType);

    //  Find records created after a specific date
    List<QuantityMeasurementEntity> findByCreatedAtAfter(LocalDateTime date);


    /*
     *  CUSTOM QUERY (JPQL)
     *
     *  @Query → write custom query using entity fields
     *  JPQL uses class name, NOT table name
     */

    @Query("SELECT q FROM QuantityMeasurementEntity q " +
           "WHERE q.operation = :operation AND q.isError = false")

    //  Get only successful operations (no errors)
    List<QuantityMeasurementEntity> findSuccessfulOperations(
            @Param("operation") String operation); //  binds value to :operation


    /*
     *  COUNT QUERY
     *
     *  Returns number of successful operations
     */
    long countByOperationAndIsErrorFalse(String operation);


    /*
     *  ERROR HISTORY
     *
     *  Fetch all failed operations
     */
    List<QuantityMeasurementEntity> findByIsErrorTrue();
    
    
}